$(document).ready(function(){
	$("#sub").hide();

$("#manutd").on('click',function(){
	find('manutd');
	$("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
	 
});
$("#tottenham").on('click',function(){
	find('tottenham');
	 $("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#bournemouth").on('click',function(){
	find('bournemouth');
	$("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#astonvilla").on('click',function(){
	find('astonvilla');
	$("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#everton").on('click',function(){
	find('everton');
	 $("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
$("#watford").on('click',function(){
	find('watford');
	 $("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#leicester").on('click',function(){
	find('leicester');
	 $("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#sunderland").on('click',function(){
	find('sunderland');
	 $("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#norwich").on('click',function(){
	find('norwich');
	$("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#crystslpalace").on('click',function(){
	find('crystalpalace');
	$("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#chelsea").on('click',function(){
	find('chelsea');
	$("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#swansea").on('click',function(){
	find('swansea');
	$("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#arsenal").on('click',function(){
	find('arsenal');
	$("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#westham").on('click',function(){
	find('westham');
	$("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#newcastle").on('click',function(){
	find('newcastle');
	$("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#southampton").on('click',function(){
	find('southampton');
	$("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#stoke").on('click',function(){
	find('stoke');
	 $("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#liverpool").on('click',function(){
	find('liverpool');
	 $("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#westbrom").on('click',function(){
	find('westbrom');
	$("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});
$("#mancity").on('click',function(){
	find('mancity');
	 $("#4").text(team.matchesPlayed);
	$("#5").text(team.sumOfGoals);
	$("#6").text(team.totalWins);
	$("#7").text(team.totalLosses);
	$("#8").text(team.totalDraw);
	$("#sub").show();
});

});